server:
  port: 8080

#Количество заявок в поиске
ms.properties.findSizeApplication: 1

sleep-task-payment: 10000
sleep-task-status: 10000

spring:
  application:
    name: rfrm-pay
    version: @project.version@

  security:
    oauth2:
      client:
        registration:
          epa-tyk-client:
            provider: epa-tyk-client
            client-id: ${TUS_EPA}
            client-secret: ${TUS_PASSW_EPA}
            authorization-grant-type: client_credentials
        provider:
          epa-tyk-client:
            token-uri: ${EPA_AM_URL}/passport/oauth2/token

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_URL}:5432/${DB_NAME}?currentSchema=rfrm_pay
    username: ${DB_USER}
    password: ${DB_PASS}
    hikari:
      connectionTimeout: ${DB_CONNECTION_TIMEOUT:30000}
      minimum-idle: ${DB_MIN_IDLE:600000}
      maximum-life: ${DB_MAX_LIFE:1800000}
      maximum-pool-size: ${DB_MAX_POOL_SIZE:3}

  jmx:
    default-domain: some
  codec:
    max-in-memory-size: 5MB
    
  liquibase:
    enabled: false
    
kafkalocal:
  bootstrap-address: "localhost:29092"

#Трассировка
ru:
  vtb:
    tstr:
      client-starter:
        enabled: ${TRACING_MODE:true}
      kafka:
        bootstrap-servers: ${TRACE_KAFKA_SERVER}

opentracing:
  jaeger:
    enabled: true
    log-spans: true
    service-name: RFRM.rfrm-pay

#Аудит
audit:
  local-mode: true #${AUDIT_LOCAL_MODE:false}
  kafka:
    bootstrap:
      server: ${AUDIT_KAFKA_SERVER}
    consumer:
      group-id: audit-management
    topic: audit
    ssl:
      enabled: true
      truststore:
        # для запуска из idea
       location: ${PATH_TRUSTSTORE}
       password: ${STORE_PASSWORD}
      keystore:
        # для запуска из idea
        location: ${PATH_KEYSTORE}
        password: ${STORE_PASSWORD}
      key:
        password: ${STORE_PASSWORD}
      truststore-type: 'JKS'
      keystore-type: 'JKS'
  default-resolver:
    sub: sub_from_kafka
    channel: channel_from_kafka
  consumer:
    initial-poll:
      time: 1000

ms.properties.infoSystemCode: ${SYSTEM_RIS_CODE}
ms.properties.infoSystemId: ${SYSTEM_RIS_ID}

management:
  metrics:
    tags:
      appName:  @project.build.finalName@
      appVersion:  @project.version@
  endpoints:
    enabled-by-default: true
    web.exposure.include: health,prometheus,metrics,info
  endpoint:
    health:
      enabled: true
      show-details: always
      probes:
        group:
          readiness:
            include: db
    shutdown.enabled: true
    restart.enabled: true
    prometheus.enabled: true
    logfile.enabled: true

logging:
  level:
    ROOT: INFO
    ru.vtb.omni: INFO
    ru.vtb.omni.ac: ${LOG_LEVEL}
    ru.vtb.msa: ${LOG_LEVEL}
    org.apache.http: INFO
    ru.vtb.omni.audit: ${LOG_LEVEL}
    ru.vtb.msa.partner: ${LOG_LEVEL}
    ru.vtb.msa.rfrm.integration: ${LOG_LEVEL}
    ru.vtb.msa.mdclogging: ${LOG_LEVEL}

product-profile-fl-accounts:
  url: ${EPA_IG_URL}
  resource:  ${GET_RESOURCE} /portfolio/portfolio-agregator/portfolio/active
  headers:
    X-INITIATOR-SERVICE: rfrm-pay
  retry:
    count: 3
    duration: 2000

audit-events:
  auditEventCodeMetadataInfoList:
    - event-code: "EXAMPLE_EVENT_CODE"
      event-type: "Отправка"
      business-object: "Название бизнес-объекта"
      business-operation: "Название бизнес операции"
      audit-event-start:
        title: "Название стартового сообщения"
        messageTemplate: "'Начало операции'"
      audit-event-success:
        title: "Название успешного сообщения"
        messageTemplate: "Успешно завершено"
      audit-event-failure:
        title: "Название ошибочного сообщени"
        messageTemplate: "Произошла ошибка: + error.message"

process.platformpay:
  kafka:
    enable: ${PROCES_PALTF_ENABLE_PAY:false}
    bootstrap:
      server: ${PROCES_PALTF_KAFKA_SERVER_PAY}
    consumer:
      group-id: "pay"
    topic:
      rfrm_core_payment_order: ${RFRM_CORE_PAYMENT_ORDER}
      rfrm_pay_function_result_reward: ${RFRM_PAY_FUNCTION_RESULT_REWARD}
      rfrm_pay_function_status_update_reward: ${RFRM_PAY_DUNCTION_STATUS_UPDATE_REWARD}
      rfrm_pay_result_reward: ${RFRM_PAY_RESULT_REWARD}
    ssl:
      enabled: true
      truststore:
        # для запуска из idea
        location: ${PATH_TRUSTSTORE_PAY}
        password: ${STORE_PASSWORD_PAY}
      keystore:
        # для запуска из idea
        location: ${PATH_KEYSTORE_PAY}
        password: ${STORE_PASSWORD_PAY}
      key:
        password: ${STORE_PASSWORD_PAY}
      truststore-type: 'JKS'
      keystore-type: 'JKS'

