server:
  port: 8081

spring:
  security:
    oauth2:
      client:
        registration:
          epa-session-client:
            provider: epa-session-client
            client-id: test@app.b2c.vtb.ru
            client-secret: EDCF-1847!$imserv
            authorization-grant-type: client_credentials
          epa-tyk-client:
            provider: epa-tyk-client
            client-id: mobc-simserv-ift@tech.b2c.vtb.ru
            client-secret: EDCF-1847!$imserv
            authorization-grant-type: client_credentials
        provider:
          epa-session-client:
            token-uri: http://localhost:8070/passport/tech/oauth2/token
          epa-tyk-client:
            token-uri: http://localhost:8070/passport/oauth2/token

audit:
  local-mode: true
  kafka:
    bootstrap:
      server: d5mobc-kfc001lk.corp.dev.vtb:9092
    consumer:
      group-id: audit-management
    topic: audit
    ssl:
      enabled: false
  # нужно только для @AuditProcess, @Audit получает эти параметры из токена
  default-resolver:
    sub: sub_from_kafka
    channel: channel_from_kafka

ms.properties.infoSystemCode: RFRM
ms.properties.infoSystemId: 1800

omni-jwt-common:
  security:
    enabled: true
  token-validate:
    enable: false
  issuers:
    epa:
      issuer: "http://epa.iss"
      url: "http://localhost:8070/jwks/epa"

opentracing:
  jaeger:
    enabled: false
    log-spans: true
    service-name: RFRM.rfrm-consultations

#Трассировка
ru:
  vtb:
    tstr:
      client-starter:
        enabled: false
      kafka:
        bootstrap-servers: "d5mobc-kfc002lk.corp.dev.vtb:9092"

ms:
  frame-link: 'gui-vtbmobile.test.vtb.ru'
  token-checking:
    enabled: false

app:
  version: 0.0.0.1

session-client:
  clientContainer: 'efrmmodork@test.vtb.ru'
  employeeContainer: 'FPCH_EPAA_TEST@test.vtb.ru'
  roleList: 'MOBC_TP_SALE,MOBC_DSA'
  base-url: 'http://localhost:8070'
  query-path: '/session'


epa-anti-replay:
  epa-endpoint: http://localhost:8070/passport/jti?{jti}

person-client:
  url: http://localhost:8070
  getPerson: /api/rb/frsvsc/cspc/v1/get
  updatePhone: /api/rb/frsvsc/cspc/v1/person/update
  headers:
    X-CSPC-RISCODE: 1847
  retry:
    count: 3
    duration: 2000

epa-auth-client:
  epa-auth-token: ""
  epa-endpoint: http://localhost:8070/epa/oauth2/token
  config:
    connection-timeout: 5000
    read-timeout: 2000
    sslEnable: false

client-dko:
  url: http://localhost:8070
  clientDko: /api/rb/prp/aggregator/v1/client/dko
  headers:
    X-TYK-API-KEY: ${TYK_API_KEY}
    X-Initiator-Service: 'mobc-sim-service'
    X-MDM-ID:
  retry:
    count: 3
    duration: 2000

consent-client:
  url: http://localhost:8070
  search: /api/cross/ascm/v1/consent/search
  headers:
    X-API-KEY: 'development-dummy-key'
    X-TYK-API-KEY: 123321
  retry:
    count: 3
    duration: 2000


cross-ref-client:
  url: http://localhost:8070
  getCross: /api/rb/frsvsc/cscr/v1/get
  createCross: /api/rb/frsvsc/cscr/v1/create
  deleteCross: /api/rb/frsvsc/cscr/v1/delete
  retry:
    count: 3
    duration: 2000

employee-client:
  url: http://localhost:8070
  get: /api/cross/bscs/v2/by-login/
  retry:
    count: 3
    duration: 2000

dossier-client:
  url: http://localhost:8070
  dossier: /api/cross/dose/dose-DoseManagementService-s-rest/v1/person/product/dossier
  retry:
    count: 3
    duration: 2000

complex-check:
  url: http://localhost:8070
  check: /api/cross/cpsl/v2/check
  headers:
    X-TYK-API-KEY: 123
  retry:
    count: 3
    duration: 2000

call-arbitration:
  url: http://localhost:8070
  check: /api/rb/rarb/publicnp/v1/create_arbtr_np
  headers:
    X-TYK-API-KEY: 123
  retry:
    count: 3
    duration: 2000

aclib:
  replication:
    enabled: false
  ac:
    token:
    service-name: kafka-astra-0388
  kafka:
    bootstrap-servers: localhost:9092
    security:
      protocol: PLAINTEXT
    ssl:
      enabled: false
      truststore:
        # при локальном запуске в режиме ssl необходимо указать абсолютный путь
        location: ''
        password: ''
      keystore:
        # при локальном запуске в режиме ssl необходимо указать абсолютный путь
        location: ''
        password: ''
      key:
        password:
      truststore-type: 'JKS'
      keystore-type: 'JKS'

logging:
  level:
    ROOT: INFO
    ru.vtb.omni: INFO
    ru.vtb.omni.ac: DEBUG
    ru.vtb.msa: DEBUG
    org.apache.http: INFO
    ru.vtb.omni.audit: INFO
    ru.vtb.msa.partner: DEBUG
    ru.vtb.msa.rfrm.integration: DEBUG
    ru.vtb.msa.mdclogging: DEBUG

splm:
  client:
    url: 'http://localhost:8070'
    urlPathDeliveryBatchSimSmlp: /api/cross/splm/process-task-for-safe/v1/completeDeliveryBatchSIM
    urlPathCheckSimStatusSmlp: /api/cross/splm/process-task-for-safe/v1/checkSIMStatus
    useSmlpCheckStatus: true
    useSmlpBatchSim: true
    retry:
      count: 3
      duration: 2000

feature.toggle:
  roleModelToggle:
    roleOn: false
  asynToggle:
    asynOn: true