apiVersion: v1
kind: Service
metadata:
  name: {{ include "service.fullname" . }}
  labels:
  {{- include "service.labels" . | nindent 4 }}
  annotations:
    description: Service for {{ .Chart.Name }}
    tsam.vtb.ru/path: '/actuator/prometheus'
    tsam.vtb.ru/port: '{{ .Values.service.actuatorPort }}'
    tsam.vtb.ru/project-code: 'RFPR'
    tsam.vtb.ru/ris-code: '1865'
    tsam.vtb.ru/scrape: 'true'
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- with .Values.service.grpcPort}}
    - port: {{ . }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    {{- end}}
    {{- with .Values.service.grpcTranscodingPort}}
    - port: {{ . }}
      targetPort: transcoding
      protocol: TCP
      name: transcoding
    {{- end}}
    {{- with .Values.service.httpPort}}
    - port: {{ . }}
      targetPort: http
      protocol: TCP
      name: http
    {{- end}}
  selector:
  {{- include "service.selectorLabels" . | nindent 4 }}
