apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app_value.name }}-config
data:
  LOGGING_CONFIG: /config/log4j2.xml
  DB_MIN_IDLE: '600000'
  PROCES_PALTF_TOPIC: test
  logging.level.com.zaxxer.hikari: INFO
  PATH_TRUSTSTORE: /app
  EPA_AM_URL: 'wiremock:8080'
  DB_MAX_POOL_SIZE: '3'
  TUS_EPA: test
  LOG_LEVEL: INFO
  PROCES_PALTF_KAFKA_SERVER: test
  PROCES_PALTF_MAX_POLL_RECORDS: '1'
  SYSTEM_RIS_ID: '2155'
  PATH_TRUSTSTORE2: test
  TUS_PASSW_EPA: test
  TRACE_KAFKA_SERVER: testurl
  EPA_IG_URL: 'wiremock:8080'
  GET_RESOURCE: /portfolio/portfolio-agregator/portfolio/active
  DB_MAX_LIFE: '1800000'
  STORE_PASSWORD: qwer
  STORE_PASSWORD2: test
  AUDIT_LOCAL_MODE: 'true'
  PATH_KEYSTORE: /app
  AUDIT_KAFKA_SERVER: testurl
  TRACING_MODE: 'false'
  SYSTEM_RIS_CODE: rfrm
  DB_CONNECTION_TIMEOUT: '30000'
  log4j2.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <configuration>
      <conversionRule conversionWord="esIndexLevelSuffix" converterClass="ru.vtb.logging.logback.plugin.EventLevelClassicConverter" />
      <appender name="TCP" class="net.logstash.logback.appender.LogstashTcpSocketAppender">
        <destination>127.0.0.1:5170</destination>
        <includeCallerData>true</includeCallerData>
        <reconnectionDelay>5000</reconnectionDelay>
        <encoder class="net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder">
          <providers>
            <pattern>
              <omitEmptyFields>true</omitEmptyFields>
              <!--
                использование полей callerClass, callerLine и callerMethod может негативно влиять на производительность
                поле encProvider может быть при необходимости добавлено в pattern
              -->
              <pattern>
                {
                      "appType": "RTL_MCRSRVCS",
                      "risCode": "2155",
                      "projectCode": "RFRM",
                      "appName": "rfrm-pay",
                      "threadName": "%thread",
                      "loggerName": "%logger",
                      "text": "%message",
                      "callerClass": "%class",
                      "callerMethod": "%method",
                      "callerLine": "#asLong{%line}",
                      "level": "%level",
                      "extEventId": "%X{extEventId}",
                      "agrType": "%X{agrType:-TRACING}",
                      "traceId": "%X{traceId}",
                      "spanId": "%X{spanId}",
                      "parentSpanId": "%X{parentSpanId}",
                      "userId": "%X{localUserId}",
                      "logicTime": "%X{logicTime}",
                      "esIndexLevelSuffix": "%esIndexLevelSuffix",
                      "callId": "%X{callId}",
                      "initiatorHost": "%X{initiatorHost}",
                      "initiatorService": "%X{initiatorService}",
                      "methodName": "%X{methodName}",
                      "unc": "%X{unc}",
                      "messageType": "%X{messageType}",
                      "account": "%X{account}",
                      "accountType": "%X{accountType}",
                      "action": "%X{action}",
                      "channel": "%X{channel}",
                      "debugMode": "%X{debugMode}",
                      "messageId": "%X{messageId}",
                      "mdmId": "%X{mdmId}",
                      "localSystemCode": "%X{localSystemCode}"
                    }
                  </pattern>
                </pattern>
                <uuid>
                  <fieldName>eventId</fieldName>
                </uuid>
                <timestamp>
                  <pattern>yyyy-MM-dd'T'HH:mm:ss.SSS</pattern>
                  <fieldName>localTime</fieldName>
                  <timeZone>UTC</timeZone>
                </timestamp>
                <logLevelValue>
                  <fieldName>levelInt</fieldName>
                </logLevelValue>
                <arguments>
                  <includeNonStructuredArguments>false</includeNonStructuredArguments>
                </arguments>
                <stackTrace>
                  <fieldName>stack</fieldName>
                </stackTrace>
                <mdc>
                  <fieldName>mdc</fieldName>
                  <excludeMdcKeyName>extEventId</excludeMdcKeyName>
                  <excludeMdcKeyName>agrType</excludeMdcKeyName>
                  <excludeMdcKeyName>traceId</excludeMdcKeyName>
                  <excludeMdcKeyName>spanId</excludeMdcKeyName>
                  <excludeMdcKeyName>parentSpanId</excludeMdcKeyName>
                  <excludeMdcKeyName>sampled</excludeMdcKeyName>
                  <excludeMdcKeyName>userId</excludeMdcKeyName>
                  <excludeMdcKeyName>logicTime</excludeMdcKeyName>
                  <excludeMdcKeyName>callId</excludeMdcKeyName>
                  <excludeMdcKeyName>initiatorHost</excludeMdcKeyName>
                  <excludeMdcKeyName>initiatorService</excludeMdcKeyName>
                  <excludeMdcKeyName>methodName</excludeMdcKeyName>
                  <excludeMdcKeyName>messageId</excludeMdcKeyName>
                  <excludeMdcKeyName>messageType</excludeMdcKeyName>
                  <excludeMdcKeyName>accountType</excludeMdcKeyName>
                  <excludeMdcKeyName>action</excludeMdcKeyName>
                  <excludeMdcKeyName>channel</excludeMdcKeyName>
                  <excludeMdcKeyName>debugMode</excludeMdcKeyName>
                  <excludeMdcKeyName>mdmId</excludeMdcKeyName>
                  <excludeMdcKeyName>localUserId</excludeMdcKeyName>
                  <excludeMdcKeyName>localSystemCode</excludeMdcKeyName>
                  <excludeMdcKeyName>unc</excludeMdcKeyName>
                </mdc>
          </providers>
        </encoder>
      </appender>
      <appender name="CONSOLE" class="ch.qos.logback.core.ConsoleAppender">
        <layout class="ch.qos.logback.classic.PatternLayout">
          <Pattern>
            %d{yyyy-MM-dd HH:mm:ss}[%thread]%-5level %logger{36} - %msg%n
          </Pattern>
        </layout>
      </appender>
      <root level="INFO">
        <appender-ref ref="TCP"/>
        <appender-ref ref="CONSOLE" />
      </root>
      <logger name="org.hibernate.SQL" level="info"/>
      <logger name="org.apache.kafka" level="info"/>
    </configuration>
