kind: ConfigMap
apiVersion: v1
metadata:
  name: rfrm-fluent-bit-config
  annotations:
    meta.helm.sh/release-name: "{{ .Values.common_values.releasename }}"
    meta.helm.sh/release-namespace: "{{ .Values.common_values.namespace }}"
  labels:
    app.kubernetes.io/managed-by: "Helm"
data:
  CLIENT_KAFKA_CERT_KEY_PASSWORD: "{{ .Values.common_values.fb.kafkacertpass | b64dec }}"
  ES_INDEX_NAME_SUFFIX: '{{ .Values.common_values.fb.namesuffix }}'
  KAFKA_BROKER: '{{ .Values.common_values.fb.fbbrokers }}'
  KAFKA_TOPICS: {{ .Values.common_values.fb.fbtopics }}
  LOG_LEVEL: {{ .Values.common_values.fb.fbloglevel }}