kind: Secret
apiVersion: v1
metadata:
  name: rfrm-fluent-bit-secret
  annotations:
    meta.helm.sh/release-name: "{{ .Values.common_values.releasename }}"
    meta.helm.sh/release-namespace: "{{ .Values.common_values.namespace }}"
  labels:
    app.kubernetes.io/managed-by: "Helm"
data:
  KAFKA_CERT_PASSWORD: "{{ .Values.common_values.fb.kafkacertpass }}"
  ca-kafka-cert.pem: {{ .Values.common_values.fb.cakafkacertpem }}
  client-kafka-cert-key.pem: {{ .Values.common_values.fb.clientkafkacertkeypem }}
  client-kafka-cert.pem: {{ .Values.common_values.fb.clientkafkacertpem }}
