kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.app_value.name }}-keystore-secret
stringData:
  keystore.jks: {{ .Values.app_value.keystore }}
  truststore.jks: {{ .Values.app_value.truststore }}

