kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.app_value.name }}-secret
stringData:
  DB_NAME: 'rfrm_pay'
  DB_USER: 'rfrm_pay_admin'
  DB_URL: 'd5rfrm-pgc001lk.corp.dev.vtb'
  DB_PASS: '7gEmkEBv3o7YID7baeMRlFo0R0YyHzlwW3U7p_F'