kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.app_value.name }}-secret
stringData:
  DB_NAME: {{ .Values.db.name }}
  DB_USER: {{ .Values.db.user }}
  DB_URL: {{ .Values.db.url }}
  DB_PASS: {{ .Values.db.pass }}
