apiVersion: operators.uir.vtb.ru/v1
kind: ServiceMeshGateway
metadata:
  name: ingress-api-gateway
spec:
  gateway:
    replicas: 1
    template:
      spec:
        containers:
          envoy:
            resources:
              limits:
                cpu: 512m
                memory: 512Mi
              requests:
                cpu: 256m
                memory: 256Mi